### ISSUE TITLE
Dialog not resizable

### ISSUE THREAD

**Issue by pcav** [klausib/xyToPoint#1]
The dialog can be expanded, but the content stays fixed. Either make the content dynamic, or fix the size of the dialog. In the current setting, the label "Layername (Input Optional) partly overlaps the input field below, in Gnome3.
See attached png.
![dialog](https://cloud.githubusercontent.com/assets/691842/6572611/bf852f5c-c713-11e4-9797-78304913c0d0.png)

**Comment by klausib** [comment]
Thank you for this hint! I will fix that.

Regards
Nikolaus

mit freundlichen Grüßen
Nikolaus Batlogg





Nikolaus Batlogg
Abteilung Geoinformation
Landesamt für Vermessung und Geoinformation
Johannitergasse 6
6800 Feldkirch
T: +43(0)5522/75482-60220
F: +43(0)5522/75482-6
E: nikolaus.batlogg@vorarlberg.at<mailto:nikolaus.batlogg@vorarlberg.at>
I: http://www.vorarlberg.at/lvg
Rechtsverbindlichen Schriftverkehr
(zB Anträge, Rechtsmittel) richten Sie an:
F: +43(0)5522/75482-6
E: landesvermessungsamt@vorarlberg.at<mailto:landesvermessungsamt@vorarlberg.at>

Von: Paolo Cavallini [mailto:notifications@github.com]
Gesendet: Dienstag, 10. März 2015 10:54
An: klausib/xyToPoint
Betreff: [xyToPoint] Dialog not resizable (#1)


The dialog can be expanded, but the content stays fixed. Either make the content dynamic, or fix the size of the dialog. In the current setting, the label "Layername (Input Optional) partly overlaps the input field below, in Gnome3.
See attached png.
[Das Bild wurde vom Absender entfernt. dialog]<https://cloud.githubusercontent.com/assets/691842/6572611/bf852f5c-c713-11e4-9797-78304913c0d0.png>

**Comment by klausib** [comment]
Please have a look at the Version 1.0.1. Version 1.0 was put into a wrong folder xyToPoint_1_0_produktiv (my mistake). If QGIS doesn't remove this folder, it should be removed manually, sorry.
