### ISSUE TITLE
Points are created assuming EPSG:4326

### ISSUE THREAD

**Issue by pcav** [klausib/xyToPoint#3]
If I create a layer from a set of coordinates in, asy, EPSG:3003, the layer is incorrectly created as EPSG:4326.

**Comment by klausib** [comment]
Could you please send me a sample as CSV.
Regards
Nikolaus


Von: Paolo Cavallini [mailto:notifications@github.com]
Gesendet: Dienstag, 10. März 2015 10:58
An: klausib/xyToPoint
Betreff: [xyToPoint] Points are created assuming EPSG:4326 (#3)


If I create a layer from a set of coordinates in, asy, EPSG:3003, the layer is incorrectly created as EPSG:4326.

**Comment by pcav** [comment]
Sent by email (no text attachments on GH, unfortunately).

**Comment by klausib** [comment]
Whenever the Plugin creates a new Memory Layer it takes the CRS that is set in the Project Properties of QGIS. No transformation is performed. Could you please test the Plugin again and compare the created Memory layer CRS with these settings?

**Comment by pcav** [comment]
Confirmed. IMHO it should take it from the layer, not from the project.

**Comment by klausib** [comment]
Which layer do you mean? The importet Databes table - for example if there is a column with EPSG Information?

**Comment by pcav** [comment]
Yes, the source layer - I did a bit of a weird thing, importing a csv file and using it as an input for the plugin; the file was in 3003, the project in 4326, so the results are wrong in my case.

**Comment by klausib** [comment]
Please have a look at the Version 1.0.1. Version 1.0 was put into a wrong folder xyToPoint_1_0_produktiv (my mistake). If QGIS doesn't remove this folder, it should be removed manually, sorry.
