### ISSUE TITLE
Error on loading qgis if your plugin is installed

### ISSUE THREAD

**Issue by marcobra** [klausib/xyToPoint#5]
With qgis 2.8.1-Wien i get error if i install your plugin, the error disappear if i remove or comment the row 

import resources_rc

at the end of file

~/.qgis2/python/plugins/xyToPoint_1_0_produktiv/mainWindow.py

Are really needed the exe files into plugin dir:
pylupdate4.exe
pyrcc4.exe
and the 
.git 
directory

Thank 
Marco Braida

**Comment by klausib** [comment]
Thanks, I zipped the wrong Directory, my fault. I will reupload the plugin.

**Comment by klausib** [comment]
Please have a look at the Version 1.0.1. Version 1.0 was put into a wrong folder xyToPoint_1_0_produktiv (my mistake). If QGIS doesn't remove this folder, it should be removed manually, sorry.

**Comment by marcobra** [comment]
The old "xyToPoint_1_0_produktiv" plugin directory will be deleted automatically by disinstalling old plugin using qgis plugin manager, so 

we don't need to manually remove the dir ~/.qgis2/python/plugins/xyToPoint_1_0_produktiv

Thank
