### ISSUE TITLE
Please add a more relevant home page

### ISSUE THREAD

**Issue by pcav** [klausib/xyToPoint#6]
rather than a generic one. If nothing more descriptive is available, the GitHub repo can be used.
Thanks.

**Comment by klausib** [comment]
I am sorry for that, but ther is no appropriate Homepage available at the moment, nor will it be in the next couple of months. If you think a Link to Github ist better, I will change the Link with the next update.

**Comment by pcav** [comment]
Yes, please.
Thanks.
